<!-- Footer logos -->

<div class="bg-white p-2">
    <div class="row mx-auto">
        <div class="mx-auto mt-3 " id="sponsors">
            <a href="http://www.museums.cam.ac.uk"><img class="img-responsive" loading="lazy"
                                                        alt="University of Cambridge Museums logo"
                                                        src="https://fitzmuseum.cam.ac.uk/images/logos/ucm_logo_black_white.png"
            ></a>
            <a href="http://www.artscouncil.org.uk/what-we-do/raising-standards/designation-scheme/"><img
                    class="img-responsive" alt="Designation scheme Logo" loading="lazy"
                    src="https://fitzmuseum.cam.ac.uk/images/logos/designation.png"
            ></a>
            <a href="http://www.artscouncil.org.uk/what-we-do/supporting-museums/accreditation-scheme/"><img
                    class="img-responsive" alt="Accredited Museum status logo" loading="lazy"
                    src="https://fitzmuseum.cam.ac.uk/images/logos/accredited.png"
            ></a>
            <a href="http://www.cambridge.gov.uk/"><img class="img-responsive" alt="Cambridge City Council Logo" loading="lazy"
                                                        src="https://fitzmuseum.cam.ac.uk/images/logos/camcity_logo.png"
            ></a>
            <a href="http://www.artscouncil.org.uk/"><img
                    class="img-responsive" alt="Arts Council England Logo" src="https://fitzmuseum.cam.ac.uk/images/logos/ace.png" loading="lazy"
            ></a>
            <a href="https://re.ukri.org/"><img class="img-responsive" alt="Research England logo" loading="lazy"
                                                src="https://fitzmuseum.cam.ac.uk/images/logos/research_england.png"
            ></a>

        </div>
    </div>
</div>
<!--- Footer stuff -->
<footer class="text-white">

    <div class="container ">
        <div class="row">
            <div class="col-sm mt-2 mb-2 border-right border-white">
                <h4>Contact us</h4>
                <p>
                    The Fitzwilliam Museum,<br/>
                    Trumpington Street,<br/>
                    Cambridge<br/>
                    CB2 1RB<br/>
                    Tel: +44 (0)1223 332900<br />
                    What3Words location: <span class="w3w"><a
                      href="https://map.what3words.com/lofts.puzzle.given"
                      aria-label="What3Words location phrase">lofts.puzzle.given</a></span>
                </p>
            </div>
            <div class="col-sm mt-2 mb-2 border-right border-white ">
                <h4>Useful links</h4>

                <ul class="share">
                    <li><a href="https://www.museums.cam.ac.uk/"
                      aria-label="The University of Cambridge museums site">University
                      of Cambridge Museums</a></li>
                    <li><a href="https://www.fitzmuseum.cam.ac.uk/aboutus/support"
                      aria-label="A link to Fitz fundraising pages">Support the Fitz</a></li>
                    <li><a href="https://www.fitzmuseum.cam.ac.uk/website/tou"
                      aria-label="Website terms and conditions">Website Terms of Use</a></li>
                    <li><a href="https://www.fitzmuseum.cam.ac.uk/website/cookiepolicy"
                      aria-label="Our privacy policy">Privacy and cookies</a></li>
                    <li><a href="https://www.fitzmuseum.cam.ac.uk/website/cookiepolicy">Accessibility</a></li>
                    <li><a aria-label="Contact the museum" href="https://fitzmuseum.cam.ac.uk/contactus">Contact us</a></li>
                    <li><a aria-label="Join our mailing list"
                      href="https://fitzmuseum.cam.ac.uk/signup">Join the Fitz email list</a></li>
                    <li><a href="https://www.registrarysoffice.admin.cam.ac.uk/governance-and-strategy/anti-slavery-and-anti-trafficking"
                           aria-label="Modern Slavery Act statement of compliance">Modern Slavery Act Statement</a>

                </ul>
            </div>
            <div class="col-sm mt-2 mb-2 border-dotted border-right border-white ">
                <h4>Talk to us</h4>
                <p class="share">
                    <a aria-label="Fitzwilliam Museum twitter account" href="https://twitter.com/FitzMuseum_UK"><i class="fab fa-twitter fa-2x p-2"></i></a>
                    <a aria-label="Fitzwilliam Museum instagram account" href="https://www.instagram.com/fitzmuseum_uk"><i class="fab fa-instagram fa-2x  p-2"></i></a>
                    <a aria-label="Fitzwilliam Museum facebook account" href="https://www.facebook.com/fitzwilliammuseum/"><i class="fab fa-facebook fa-2x p-2"></i></a>
                    <a aria-label="Fitzwilliam Museum github account" href="https://www.github.com/{{ site.github_username }}/{{ site.github_repo }}"><i
                            class="fab fa-github fa-2x p-2"></i></a>
                </p>
                <h4>Watch and listen</h4>
                <p class="share">
                    <a aria-label="Watch our YouTube videos" href="https://www.youtube.com/channel/UCFwhw5uPJWb4wVEU3Y2nScg"><i
                            class="fab fa-youtube fa-2x p-2"></i></a>
                </p>
            </div>
            <div class="col-sm mt-2 mb-2">
                <a aria-label="The main Fitzwilliam website" href="https://www.fitzmuseum.cam.ac.uk"><img alt="Fitzwilliam Museum logo" src="https://fitzmuseum.cam.ac.uk/images/logos/FitzwilliamLogoFooter.png" loading="lazy" class="rounded d-block"/></a>
                <p class="share">
                    &copy; 2022 The University of Cambridge<br/>
                    Content: CCBY<br />
                    Code: GPLv3
                </p>
            </div>
        </div>
    </div>

    <a href="#0" class="cd-top js-cd-top">Top</a>

</footer>
