<a class="sr-only sr-only-focusable doc-skip" href="#doc-main-h1">
    <div class="container">
        <span class="doc-skip-text">Skip to main content</span>
    </div>
</a>
  <!-- Nav bars -->
<nav class="navbar navbar-expand-lg navbar-dark bg-black fixed-top">
  <a class="navbar-brand" href="https://www.fitzmuseum.cam.ac.uk">
    <img src="https://www.fitzmuseum.cam.ac.uk/images/logos/Fitz_logo_white.png" alt="The Fitzwilliam Museum Logo" height="60" width="66.66" class="ml-1 mr-1">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
  aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="https://www.fitzmuseum.cam.ac.uk">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item ">
      <a class="nav-link" href="https://www.fitzmuseum.cam.ac.uk/visit-us" >Visit</a>
    </li>
    <li class="nav-item ">
      <a class="nav-link" href="https://www.fitzmuseum.cam.ac.uk/events">Events & tickets</a>
    </li>

    <li class="nav-item ">
      <a class="nav-link" href="https://www.fitzmuseum.cam.ac.uk/objects-and-artworks">Our Collection</a>
    </li>
    <li class="nav-item ">
      <a class="nav-link" href="https://www.fitzmuseum.cam.ac.uk/learning">
      Learning</a>
    </li>
    <li class="nav-item ">
      <a class="nav-link " href="https://www.fitzmuseum.cam.ac.uk/about-us">
      About</a>
    </li>
    <li class="nav-item ">
      <a class="nav-link " href="https://www.fitzmuseum.cam.ac.uk/support-us">
      Support Us</a>
    </li>
    <li class="nav-item ">
      <a class="nav-link" href="https://www.fitzmuseum.cam.ac.uk/research">Research</a>
    </li>
    <li class="nav-item ">
      <a class="nav-link" href="https://curatingcambridge.co.uk/collections/the-fitzwilliam-museum">Shop</a>
    </li>
</ul>
<form method="GET" action="https://www.fitzmuseum.cam.ac.uk/search/results" accept-charset="UTF-8" class="form-inline ml-auto">
  <label for="search" class="sr-only">Search: </label>
  <input id="query" name="query" type="text" class="form-control mr-sm-2"
  placeholder="Search our site" required value="" aria-label="Your query">
  <button type="submit" class="btn btn-outline-light my-2 my-sm-0" id="searchButton" aria-label="Submit your search">Search</button>
</form>
</div>
</nav>
  <div class="container-fluid head parallax">
</div>
<div class="container-fluid bg-white text-black text-center">
  <div class="py-2">
    <h1 class="shout lead" id="doc-main-h1"><?php echo $escape($site->title()); ?></h1>
  </div>
</div>
  <div class="container-fluid bg-maroon text-white p-1">
  <div class="container">
    <div class="text-center my-2">
      <a class="text-center btn btn-outline-light" href="https://tickets.museums.cam.ac.uk/overview/generaladmission">
        <i class='fas fa-ticket-alt mr-2' aria-hidden='true' title='ticket'></i><span class='sr-only'>ticket</span>  Visiting us? Booking required - Free Entry
      </a>
    </div>

    <p class="text-center text-black">
      Tuesday - Saturday: 10:00 - 17:00 |
      Sundays and Bank Holiday Mondays: 12:00 - 17:00 |   Box office closed Mondays
      <br />
      Closed 24th December to 27th December 2021 and 31st December 2021 to 1st January 2022 inclusive
      <i class='fas fa-door-closed ' aria-hidden='true' title='closed'></i><span class='sr-only'>closed</span> <a class="free_ticket" href="https://www.fitzmuseum.cam.ac.uk/visit-us/gallery-closures-and-collection-updates" >Gallery closures and collection updates</a>
    </p>
  </div>
</div>
