<a class="sr-only sr-only-focusable doc-skip" href="#doc-main-h1">
    <div class="container">
        <span class="doc-skip-text">Skip to main content</span>
    </div>
</a>
<!-- Nav bars -->
<nav class="navbar navbar-expand-lg navbar-dark bg-black fixed-top">
  <a class="navbar-brand" href="https://www.fitzmuseum.cam.ac.uk">
    <img src="https://www.fitzmuseum.cam.ac.uk/images/logos/Fitz_logo_white.png" alt="The Fitzwilliam Museum Logo" height="60" width="66.66" class="ml-1 mr-1">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
  aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav mr-auto">
    <?php echo $site->publicNav()->menu()->renderMenu(); ?>
    <li class="nav-item active">
      <a class="nav-link" href="https://www.fitzmuseum.cam.ac.uk">Home <span class="sr-only">(current)</span></a>
    </li>

</ul>

</div>
</nav>
<div class="container-fluid bg-white text-black text-center py-5">
  <div class="py-2">
    <h1 class="shout lead" id="doc-main-h1">Black People in European Sculpture Project</h1>
  </div>
</div>
