
<?php
$translate = $this->plugin('translate');
?>

<?php if ($totalCount): ?>
    <nav>
        <ul class="pagination Page navigation justify-content-center p-2">
            <?php if ($currentPage != 1): ?>
                <li class="page-item disabled" aria-disabled="true" aria-label="Previous page">
                    <span class="page-link" aria-hidden="true">&lsaquo;</span>
                </li>
            <?php else: ?>
                <li class="page-item">
                  <?php echo $this->hyperlink('', $previousPageUrl, ['class' => 'page-link', 'title' => $translate('Previous'), 'aria-label' => $translate('Previous')]); ?>
                </li>
            <?php endif; ?>
            <?php if ($currentPage < $pageCount): ?>
            <?php echo $this->hyperlink('', $nextPageUrl, ['class' => 'page-link', 'title' => $translate('Next'), 'aria-label' => $translate('Next')]); ?>
            <?php else: ?>
              <li class="page-item disabled" aria-disabled="true" aria-label="Next page">
                  <span class="page-link" aria-hidden="true">&rsaquo;</span>
              </li>
            <?php endif; ?>
        </ul>
    </nav>
  <?php else: ?>
      <?php echo $translate('0 results'); ?>
  <?php endif; ?>
