  <?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css', 'screen', true, ['crossorigin' => 'anonymous', 'integrity' => 'sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2']);
$this->headLink()->prependStylesheet('https://use.fontawesome.com/releases/v5.5.0/css/all.css', 'screen', true, ['crossorigin' => 'anonymous', 'integrity' => 'sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU']);
$this->headLink()->prependStylesheet($this->assetUrl('css/site.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css2?family=Libre+Baskerville:ital@1&family=Rubik&Roboto:wght@300;400;500;700&Space+Grotesk:wght@500&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js', 'text/javascript', ['integrity' => 'sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx','crossorigin' => 'anonymous']);
$this->headScript()->prependFile('https://code.jquery.com/jquery-3.5.1.slim.min.js', 'text/javascript', ['integrity' => 'sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj','crossorigin' => 'anonymous']);
$this->inlineScript()->prependFile($this->assetUrl('js/klaro.js'));
$this->inlineScript()->prependFile($this->assetUrl('js/config.js'));
$this->inlineScript()->prependFile($this->assetUrl('js/backtotop.js'));
$this->inlineScript()->prependFile($this->assetUrl('js/offcanvas.js'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php if ($this->themeSetting('accent_color') !== '' || $this->themeSetting('nav_color') !== ''): ?>
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a {
                color: <?php echo $accentColor; ?>
            }

            input[type="submit"]:hover,
            button:hover,
            .button:hover,
            .sub-menu a:hover,
            .site-page-pagination a:hover,
            a.advanced-search:hover {
                background-color: <?php echo $accentColor; ?>
            }
            <?php endif; ?>

            <?php if ($navColor = $this->themeSetting('nav_color')): ?>
            .oc-menu {
                background-color: <?php echo $navColor; ?>
            }
            <?php endif; ?>
            .head {
      background-image: url('https://content.fitz.ms/fitz-website/assets/gallery_26_odundo.jpg');
      background-repeat: no-repeat;
      background-size: cover;
      background-position: 50% 30%;
    }

        </style>
        <?php endif; ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    <?php echo $this->partial('common/header'); ?>
    <div class="container-fluid">
        <div id="oc-container" class="oc-container container">
            <div class="oc-pusher">
                <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
                <?php echo $userBar; ?>
                <header role="banner">
                    <h1>
                        <a href="<?php echo $site->url(); ?>" class="site-title">
                        <?php if ($this->themeSetting('logo')): ?>
                            <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
                        <?php else: ?>
                            <?php echo $escape($siteTitle); ?>
                        <?php endif; ?>
                        </a>
                    </h1>
                    <?php echo $this->partial('common/search-form'); ?>
                    <div id="oc-trigger">
                        <button id="menu-button" class="o-icon-menu" data-effect="oc-push" aria-label="<?php echo $this->translate('Menu'); ?>"></button>
                    </div>
                    <nav id="menu" class="oc-menu oc-push" role="navigation">
                        <?php echo $site->publicNav()->menu()->renderMenu(); ?>
                    </nav>
                </header>

                <main class="oc-content" role="main">
                  <div class="oc-content-inner">
                    <div id="content" role="main">
                      <?php echo $this->content; ?>
                    </div>
                  </div>
                </main>
            </div>
        </div>
      </div>
        <?php echo $this->partial('common/footer'); ?>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
