<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css', 'screen', true, ['crossorigin' => 'anonymous', 'integrity' => 'sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2']);
$this->headLink()->prependStylesheet('https://use.fontawesome.com/releases/v5.5.0/css/all.css', 'screen', true, ['crossorigin' => 'anonymous', 'integrity' => 'sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU']);
$this->headLink()->prependStylesheet($this->assetUrl('css/site.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css2?family=Libre+Baskerville:ital@1&family=Rubik&Roboto:wght@300;400;500;700&Space+Grotesk:wght@500&display=swap');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js', 'text/javascript', ['integrity' => 'sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx','crossorigin' => 'anonymous']);
$this->headScript()->prependFile('https://code.jquery.com/jquery-3.5.1.slim.min.js', 'text/javascript', ['integrity' => 'sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj','crossorigin' => 'anonymous']);
$this->inlineScript()->prependFile($this->assetUrl('js/klaro.js'));
$this->inlineScript()->prependFile($this->assetUrl('js/config.js'));
$this->inlineScript()->prependFile($this->assetUrl('js/backtotop.js'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
<head>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php if ($this->themeSetting('accent_color') !== '' || $this->themeSetting('nav_color') !== ''): ?>
    <style>
    <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
    a {
      color: <?php echo $accentColor; ?>
    }

    input[type="submit"]:hover,
    button:hover,
    .button:hover,
    .sub-menu a:hover,
    .site-page-pagination a:hover,
    a.advanced-search:hover {
      background-color: <?php echo $accentColor; ?>
    }
    <?php endif; ?>

    <?php if ($navColor = $this->themeSetting('nav_color')): ?>
    .oc-menu {
      background-color: <?php echo $navColor; ?>
    }
    <?php endif; ?>

    </style>
  <?php endif; ?>
  <style>

  #user-bar {
    background-color: #343a40!important;
  }
  #user-bar .admin:not(:last-child):after {
    content: "/";
    margin: 0 12px;
    color: white;
  }
  </style>
  <?php echo $this->headScript(); ?>
</head>

<body class="bg-grey">
  <?php echo $this->partial('common/header'); ?>
  <div class="container-fluid bg-dark py-3">
    <?php echo $userBar; ?>
  </div>
  <div class="container-fluid py-3">
    <div id="oc-container" class="oc-container container">
      <div class="oc-pusher col-12 shadow-sm p-3 mx-auto mb-3">

        <?php
        //echo $this->partial('common/search-form');
        ?>

        <main class="oc-content" role="main">
          <div class="oc-content-inner">
            <div id="content" role="main">
              <?php echo $this->content; ?>
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
  <?php echo $this->partial('common/footer'); ?>
  <?php echo $this->inlineScript(); ?>
</body>
</html>
